export const COMPLETION_PHRASES = [
    "Love logged. See you tomorrow",
    "You did great today — she'll feel it.",
    "Consistency is quiet romance.",
    "Lovely's proud of you.",
    "Tiny gestures, big ripples.",
    "Done for today — rest easy.",
    "That's how love compounds.",
    "You made her day brighter",
    "Your effort today keeps love alive.",
    "Beautiful consistency.",
    "She noticed. Trust that.",
    "Another day, another moment of connection.",
    "You're building something lasting.",
    "Love is in the details. Well done.",
    "That's what commitment looks like.",
    "You showed up today. That matters.",
    "Small acts, deep roots.",
    "This is how bonds strengthen.",
    "You're creating a pattern of care.",
    "Thoughtfulness completed.",
    "Tomorrow's another chance to connect.",
    "You're learning her love language.",
    "Presence over perfection — you nailed it.",
    "One more brick in your shared foundation.",
    "She'll remember this.",
    "That's the kind of partner you are.",
    "Consistency wins. Always.",
    "You're making love a daily practice.",
    "See you tomorrow for another gesture.",
    "Love isn't loud — it's this.",
];